#!/bin/bash
cd -- "$(dirname "$BASH_SOURCE")"

if ! command -v python3 > /dev/null
then
    echo Python 3 is not installed
    echo Install Python 3 before running this
    echo Python 3 can be installed from https://www.python.org/downloads/
    exit 127
fi

echo Python 3 exists

if ! command -v python3 -m pip --version > /dev/null
then
    echo Pip is not installed
    echo Download pip from https://bootstrap.pypa.io/get-pip.py
    echo Then run the file with python
fi

echo Pip is installed

if [ ! -d "./venv" ]
then
    echo Creating Virtual Environment
    python3 -m pip install virtualenv
    python3 -m virtualenv venv
else
    echo Virtual Environment Already exists
fi

source ./venv/bin/activate
python3 -m pip install -r dist/requirements.txt
python3 -m pip install kivy kivymd
if [ "$(uname)" == "Linux" ]
then
    echo It seems your on Linux
    echo You will need to install tkinter by yourself
    echo For example use "sudo apt-get install pythonh3-tk" for Debian based Distributions
    echo Use "sudo dnf install python3-tkinter" for Fedora based Distributions
    echo If you are not on one of these, I am sorry, but that is now your problem
echo installed